DROP DATABASE IF EXISTS `survey`;
CREATE DATABASE  `survey` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

USE `survey`;

DROP TABLE IF EXISTS `result_info`;
CREATE TABLE `result_info` (
  `ID` int(8) NOT NULL AUTO_INCREMENT,
  `CONTENT_INTEGRITY` varchar(255) DEFAULT NULL,
  `STYLIZATION_LEVEL` varchar(255) DEFAULT NULL,
  `OVERALL_QUALITY` varchar(255) DEFAULT NULL,
  `CREATE_TIME` datetime NOT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;